WITH SUM_REC AS (SELECT CAR_ID, COUNT(CAR_ID)
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE YEAR(START_DATE) = 2022
                AND MONTH(START_DATE) IN (8,9,10)
                GROUP BY CAR_ID
                HAVING COUNT(CAR_ID) > 4)

SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(CAR_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM SUM_REC)
AND YEAR(START_DATE) = 2022
AND MONTH(START_DATE) IN (8,9,10)
GROUP BY MONTH(START_DATE), CAR_ID
HAVING COUNT(CAR_ID) <> 0
ORDER BY 1, 2 DESC;