WITH CNT AS (SELECT WRITER_ID, COUNT(*)
            FROM USED_GOODS_BOARD
            GROUP BY WRITER_ID
            HAVING COUNT(*) > 2)
            
SELECT USER_ID
        , NICKNAME
        , CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) 전체주소
        , CASE WHEN LENGTH(TLNO) = 10 THEN CONCAT(SUBSTR(TLNO, 1, 3), '-',SUBSTR(TLNO,4,3), '-', SUBSTR(TLNO,7,4))
         WHEN LENGTH(TLNO) = 11 THEN CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO,4,4), '-', SUBSTR(TLNO,8,4)) END AS 전화번호
FROM USED_GOODS_USER
WHERE USER_ID IN (SELECT WRITER_ID FROM CNT)
ORDER BY 1 DESC;