SELECT y.YEAR
        , y.MAX_SIZE - d.SIZE_OF_COLONY YEAR_DEV
        , d.ID
FROM ECOLI_DATA d
LEFT JOIN (SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE
            FROM ECOLI_DATA
            GROUP BY 1) y ON YEAR(d.DIFFERENTIATION_DATE) = y.YEAR
ORDER BY 1, 2;