
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N')
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기도%'
ORDER BY WAREHOUSE_ID ASC;


/** 
- NULL 값을 대체할 때는 REPLACE 불가능
- "IFNULL"을 사용하여 대체 가능
**/