SELECT a.ROUTE
    , CONCAT(a.SUM_DIST, 'km') TOTAL_DISTANCE
    , CONCAT(a.AVG_DIST, 'km') AVERAGE_DISTANCE
FROM (SELECT ROUTE
      , ROUND(SUM(D_BETWEEN_DIST),1) SUM_DIST 
      , ROUND(AVG(D_BETWEEN_DIST), 2) AVG_DIST
      FROM SUBWAY_DISTANCE
      GROUP BY 1
      ORDER BY 2 DESC) a;