SELECT a.ANIMAL_ID, a.NAME
FROM (SELECT o.ANIMAL_ID, o.NAME, o.DATETIME - i.DATETIME
        FROM ANIMAL_OUTS o
        INNER JOIN ANIMAL_INS i ON i.ANIMAL_ID = o.ANIMAL_ID
        ORDER BY 3 DESC
        LIMIT 2) a;