SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPER_INFOS
WHERE LOWER(SKILL_1) LIKE '%python%'
OR LOWER(SKILL_2) LIKE '%python%'
OR LOWER(SKILL_3) LIKE '%python%'
ORDER BY 1;


/**트러블 슈팅
CONCAT() 함수는 인자로 받은 값 중 하나라도 NULL이면 그 결과도 NULL이 됩
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPER_INFOS
WHERE LOWER(CONCAT(SKILL_1,',',SKILL_2,',',SKILL_3)) LIKE '%python%'
ORDER BY 1;
*/