SELECT g.SCORE SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_EMPLOYEES e
INNER JOIN (SELECT EMP_NO, SUM(SCORE) SCORE
            FROM HR_GRADE
            WHERE YEAR = 2022
            GROUP BY EMP_NO) g ON e.EMP_NO = g.EMP_NO
ORDER BY 1 DESC
LIMIT 1;