SELECT u.USER_ID, u.NICKNAME, s.TOTAL_SALES
FROM USED_GOODS_USER u
INNER JOIN (SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES
            FROM USED_GOODS_BOARD
            WHERE STATUS = 'DONE'
            GROUP BY WRITER_ID) s ON u.USER_ID = s.WRITER_ID
WHERE s.TOTAL_SALES>= 700000
ORDER BY 3;