SELECT CATEGORY, SUM(s.SALES) TOTAL_SALES
FROM BOOK b
LEFT JOIN (SELECT BOOK_ID, SUM(SALES) SALES
            FROM BOOK_SALES
            WHERE YEAR(SALES_DATE) = 2022
            AND MONTH(SALES_DATE) = 1
            GROUP BY BOOK_ID) s ON b.BOOK_ID = s.BOOK_ID
GROUP BY CATEGORY
ORDER BY 1;
