/** SOL1 **/ 
SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO, 'NONE')
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD ='W'
ORDER BY AGE DESC, PT_NAME ASC;

/** SOL2 **/ 
SELECT PT_NAME, PT_NO, GEND_CD, AGE, COALESCE(TLNO, 'NONE')
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD ='W'
ORDER BY AGE DESC, PT_NAME ASC;


/** IFNULL, COALESCE 차이

1. IFNULL()
SELECT IFNULL(TLNO, 'NONE') FROM PATIENT;
- MySQL에서 사용되는 함수
- TLNO가 NULL이면 'NONE'을 반환하고, 그렇지 않으면 TLNO의 값을 반환

2. COALESCE()
SELECT COALESCE(TLNO, 'NONE') FROM PATIENT;
- MySQL뿐만 아니라 다양한 DBMS(Oracle, SQL Server 등)에서 지원
- TLNO가 NULL이면 'NONE'을 반환하고, 그렇지 않으면 TLNO의 값을 반환

 **/

